# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

MAILER_EMAIL: 'Yuuki @ InnoSpace <no-reply@innospace.com>'
SMTP_ADDRESS: 'smtp.mailgun.org'
SMTP_PORT: '587'
SMTP_UID: 'postmaster@sandboxf1d93c59552d4213b240fa896e3bf862.mailgun.org'
SMTP_PWD: 'ebef9def773e8fc58847cdfacb499afe'
SMTP_AUTH: 'login'
FB_APP_ID: '955947364498511'
FB_APP_PWD: '8c1afbf9b3f9a00742048fd356df8086'
G+_APP_ID: '296583770488-l5s4ms002flgf0e38rhuiktgu8g71m8m.apps.googleusercontent.com'
G+_APP_PWD: 'gPnqFBKZgaVVkzODf7_C3uXo'
S_KEY: 'sk_test_no3UciywVVwxgEhN1LmWmKrl'
P_KEY: 'pk_test_suwV5AlOOCWIM9dhlKLb9pxX'
